apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-4-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app-4
    spec:
      containers:
        - name: app-4
          image: regner/kubernetes-demo-app-4:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: KUBEDEMO_ONE
              valueFrom:
                configMapKeyRef:
                  name: app-4-configmap
                  key: one
            - name: KUBEDEMO_HELLO
              valueFrom:
                configMapKeyRef:
                  name: app-4-configmap
                  key: hello
            - name: KUBEDEMO_SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-4-secret
                  key: username
            - name: KUBEDEMO_SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-4-secret
                  key: password
